name: Train model
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  train-job:
    runs-on: ubuntu-latest 
    environment:
      name: dev 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: install az ml extension
      run: az extension add -n ml -y
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: set current directory
      run: cd code
    - name: run-pipeline
      run: run_id=$(az ml job create --file code/aml_service/nyc-taxi/pipeline.yml --resource-group osomorog --workspace-name stages-demo  --query name -o tsv)
  
  register-model-job:
      needs: train-job
      environment: 
        name: staging
        url: $run_id
      runs-on: ubuntu-18.04
      steps:
      - name: check-out-repo-step
        uses: actions/checkout@v2
      - name: install az ml extension
        run: az extension add -n ml -y
      - name: azure-login-step
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: set-azureml-ws-context-step
        run: cd code
      - name: create-model-step
        id: create-model-step
        run: az ml model create -n mlops-model -l latest -p runs:/$run_id/model --type mlflow_model --resource-group osomorog --workspace-name stages-demo
          